# Generated by Django 4.2.11 on 2024-04-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="temp", field=models.IntegerField(default=0),
        ),
    ]
