# Generated by Django 4.2.11 on 2024-04-17 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_temp"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="temp",),
    ]
