# Generated by Django 4.2.11 on 2024-04-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitem_order_remove_orderitem_product_and_more"),
        ("shop", "0003_remove_product_temp"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="categorytranslation", unique_together=None,
        ),
        migrations.RemoveField(model_name="categorytranslation", name="master",),
        migrations.RemoveField(model_name="product", name="category",),
        migrations.AlterUniqueTogether(
            name="producttranslation", unique_together=None,
        ),
        migrations.RemoveField(model_name="producttranslation", name="master",),
        migrations.DeleteModel(name="Category",),
        migrations.DeleteModel(name="CategoryTranslation",),
        migrations.DeleteModel(name="Product",),
        migrations.DeleteModel(name="ProductTranslation",),
    ]
