# Generated by Django 4.2.11 on 2024-04-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_temporarymodel_temporarymodeltranslation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="temporarymodeltranslation", unique_together=None,
        ),
        migrations.RemoveField(model_name="temporarymodeltranslation", name="master",),
        migrations.DeleteModel(name="TemporaryModel",),
        migrations.DeleteModel(name="TemporaryModelTranslation",),
    ]
