# Generated by Django 4.2.11 on 2024-04-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="order",),
        migrations.RemoveField(model_name="orderitem", name="product",),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="OrderItem",),
    ]
