# Generated by Django 4.2.20 on 2025-03-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="ranking",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="image",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
