# Generated by Django 4.2.11 on 2024-04-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_comment_comment_posts_comme_created_aa6d8f_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["-created"],
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
