name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_DB: ${{ secrets.REDIS_DB }}
      CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
      CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
      STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      STRIPE_API_VERSION: ${{ secrets.STRIPE_API_VERSION }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # С использованием образа из Docker Hubvт
      # - name: Pull Docker image
      #   run: |
      #     docker pull lemon1964/mysite:latest

      - name: Set up Docker
        run: |
          docker build -t mysite .

      - name: Check secrets
        run: |
          echo ${{ secrets.SECRET_KEY }}
          echo ${{ secrets.DATABASE_URL }}

      - name: Check environment variables
        run: |
          echo $DATABASE_URL
          echo $POSTGRES_DB

      - name: Check environment variables inside Docker
        run: |
          docker run --rm -v $(pwd):/code \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            mysite env
        
        
      - name: Run migrations
        run: |
          docker run --rm -v $(pwd):/code \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e POSTGRES_DB="${{ secrets.POSTGRES_DB }}" \
            -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e REDIS_HOST="${{ secrets.REDIS_HOST }}" \
            -e REDIS_PORT="${{ secrets.REDIS_PORT }}" \
            -e REDIS_DB="${{ secrets.REDIS_DB }}" \
            -e CELERY_BROKER_URL="${{ secrets.CELERY_BROKER_URL }}" \
            -e CELERY_RESULT_BACKEND="${{ secrets.CELERY_RESULT_BACKEND }}" \
            -e STRIPE_PUBLISHABLE_KEY="${{ secrets.STRIPE_PUBLISHABLE_KEY }}" \
            -e STRIPE_SECRET_KEY="${{ secrets.STRIPE_SECRET_KEY }}" \
            -e STRIPE_API_VERSION="${{ secrets.STRIPE_API_VERSION }}" \
            -e STRIPE_WEBHOOK_SECRET="${{ secrets.STRIPE_WEBHOOK_SECRET }}" \
            -e EMAIL_HOST_USER="${{ secrets.EMAIL_HOST_USER }}" \
            -e EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}" \
            -e SOCIAL_AUTH_GOOGLE_OAUTH2_KEY="${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY }}" \
            -e SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET="${{ secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET }}" \
            mysite python /code/mysite/manage.py migrate --noinput
          
            
      - name: Trigger Render deployment
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
