# Generated by Django 4.2.11 on 2024-04-17 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_orderitem_order_remove_orderitem_product_and_more"),
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Coupon",),
    ]
